// eslint-disable-next-line @typescript-eslint/no-var-requires
const fs = require("fs");

const filePath = "src/util/metadata.ts";
const contents = `// This file has been generated by NPM

export const sdkVersion = "${process.env.npm_package_version}";

const projectName = "${process.env.npm_package_name}";

export const sdkIdentifier = \`\${projectName}/v\${sdkVersion}\`;
`;

fs.writeFileSync(filePath, contents, "utf-8");
